### ISSUE TITLE
vi-mode section not working as external section

### ISSUE THREAD

**Issue by ivanterrible** [spaceship-prompt/spaceship-vi-mode#2]
In the current version of spaceship-prompt v4 the vi-mode section does not update (it will always show insert mode).
Following the instructions in the README.md does not produce the desired result of prompt changing when vi-mode changes.

With the following change to the main plugin file I was able to get it to function.

```zsh
spaceship_vi_mode_enable() {
  function zle-keymap-select() { zle reset-prompt ; zle -R }
  zle -N zle-keymap-select
  bindkey -v
}
``` 
Modified to

```zsh
spaceship_vi_mode_enable() {
  function zle-keymap-select() { spaceship::core::refresh_section "vi_mode" ; zle .reset-prompt && zle -R }
  zle -N zle-keymap-select
  bindkey -v
}
``` 

Have not dug any further for potential issues.

**Comment by GiuseppeMP** [comment]
@ivanterrible Thx! 
Same issue here, now I'm using your solution temporally, while the bug exists.

**Comment by denysdovhan** [comment]
@GiuseppeMP you're welcome to contribute. `spaceship_vi_mode_enable` is exactly the function for enabling vi-mode.

**Comment by ivanterrible** [comment]
@denysdovhan 
 
Let me provide some further clarification, on this issue `eval spaceship_vi_mode_enable` as it is now does not enable the functionality to work.  The change that I made and listed above is a change to the `spaceship_vi_mode_enable` function that would allow `eval spaceship_vi_mode_enable` it to work as this did when vi-mode was integrated.

Sure, I can create a pull request with the above change.
